name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  print:
    runs-on: ubuntu-lastest
    steps:
      - name: Step1
        run: echo "The ID key is:$CLIENT_ID"
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Start App
        run: npm run start
